server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Leitet alle Anfragen, die keine echten Dateien sind, an die index.html weiter
    location / {
        try_files $uri $uri/ /index.html;
    }
}