version: '3.8'

networks:
  fitness-network:
    driver: bridge
  proxy_net:
    external: true # Wichtig: Nutzt das Netzwerk, das wir vorhin erstellt haben

services:
  backend:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_IP}:${DB_PORT}/${DB_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=https://lucaslabs.dev
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - CSRF_SECRET=${CSRF_SECRET}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
    restart: unless-stopped
    networks:
      - fitness-network
      - proxy_net # Damit der Proxy das Backend erreichen kann

  frontend:
    build: 
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - VITE_API_URL: "https://api.lucaslabs.dev"
        - VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fitness-network
      - proxy_net

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy_net